language: go
# Travis Xenial doesn't support disabling sudo, that's ability is
# a relic of previous container-based non-ByoDocker builds.

go:
- 1.14.x
# FIXME: TEMPORARY DISABLE WHILE ITERATING AND DEBUGGING
#- 1.13.x
#- 1.12.x

install:
- go get -t ./...
- go get github.com/mattn/goveralls
- go get github.com/wadey/gocovmerge
- go get -u honnef.co/go/tools/cmd/staticcheck
- go get -u github.com/client9/misspell/cmd/misspell

before_script:
- $(exit $(go fmt ./... | wc -l))
- go vet ./...
- misspell -error -locale US .
- staticcheck ./...
# Beware that this will install, then curl itself a second time and run through the steps silently:
- [[ ! "$TRAVIS_GO_VERSION" =~ 1.14 ]] || "curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | sudo bash"


script:
- [[ ! "$TRAVIS_GO_VERSION" =~ 1.14 ]] || fossa init
- [[ ! "$TRAVIS_GO_VERSION" =~ 1.14 ]] || fossa analyze
- go test -v -race ./...
- [[ ! "$TRAVIS_GO_VERSION" =~ 1.14 ]] || ./scripts/cov.sh TRAVIS
# This one blocks the build until fossa analysis completes
- [[ ! "$TRAVIS_GO_VERSION" =~ 1.14 ]] || fossa test
